name = "HijriConverter"
uuid = "1684ca53-84b9-4d6f-b1d0-0dc9aead1b39"
authors = ["ceferisbarov <-l>"]
version = "0.2.0+REDO"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Parameters = "0.12.3"
julia = "1.7.0"
